Basically, the aim of the task is to share the results (accuracy score/performance) of two machine learning model i.e Support Vector Machine and Stochastic Gradient Descent Method.But,I have used many other classification algorithms to see which performs the best among all the algorithms.
The datasets was provided to perform the task.It was boardly divided such that 60% of data was for training the model,20% of data was to validate the model such that we can tune its hyperparameters and its performance is improved and the rest 20% was for testing purpose.

So Let's code:

Importing all the modules/packages required to complete the given task

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression,SGDClassifier
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.gaussian_process import  GaussianProcessClassifier
from sklearn.preprocessing import StandardScaler 
from sklearn.metrics import accuracy_score,precision_score,recall_score,confusion_matrix,f1_score,classification_report


This is the model-1 which performs the KNearest algorithm.In this model-1,the performance of KNN on the given task is improved
Firstly,the datasets is provided with all necessary cleaning and converting to numpy array.I have set a range of values for which ,it will tune the value of k on the validation set such that we can know the value of k whichs performs the best on the validation set.Then we used the best value  of k for testing purposes and calculate the accuracy of the model,which comes to be in between 93 and 94 percent.  

In [2]:
def model1(x_train,y_train,x_val,y_val,x_test,y_test):
    k_range=[5,7,10,12,18,25]                              #different value of k in knn and to obtain the best suitable value
    a=[]
    for i in k_range:
        knn=KNeighborsClassifier(n_neighbors=i)
        knn.fit(x_train,y_train)
        y_val_pred=knn.predict(x_val)
        acc=round(accuracy_score(y_val_pred,y_val),4)*100
        a.append(acc)                                     #appending accuracy obtained from  training the model with different parameter
    m=max(a)      #getting the maximum accuracy from validation set                          
    p=a.index(m)  #getting the index of the max_accuracy
    knn=KNeighborsClassifier(n_neighbors=k_range[p]) #again training the model with best hyperparameter
    x_train=np.concatenate((x_train,x_val))  #Now combining both training and validation data
    y_train=np.concatenate((y_train,y_val))  #Now combing the target values of training and validation data
    knn.fit(x_train,y_train) #fitting the training data into model
    y_test_pred=knn.predict(x_test)
    print("Model-1 : K-Nearest Neighbors")
    acc_t=round(accuracy_score(y_test_pred,y_test),4)*100 #accuracy from accuracy_score
    print("Accuracy of Model 1 on test set : ",acc_t)
    pre=round(precision_score(y_test_pred,y_test,average='macro'),4)*100 #precision of the model
    print("Precision of Model 1 on test set : ",pre)
    rec=round(recall_score(y_test_pred,y_test,average='macro'),4)*100  #recall of the model
    print("Recall of Model 1 on test set : ",rec)
    f_score=round(f1_score(y_test_pred,y_test,average='macro'),4)*100  #f1_score of the model
    print("F1-score of Model-1 on test set : ",f_score)
    con_mat=confusion_matrix(y_test,y_test_pred,labels=[1,2,3,4,5,6,7,8]) #confusion-matrix of the model
    print("Confusion Matrix of Model-1 on test set : ")
    print(con_mat)
    print(classification_report(y_test,y_test_pred,digits=8))
    
    
        
        
    
    
    

The model-2 performs the Logistic-Regression on the given task and tuning is done using simple loops and the accuracy comes out to be in beween 92 and 93.

In [3]:
def model2(x_train,y_train,x_val,y_val,x_test,y_test):
    solver=['liblinear','newton-cg','sag','saga','lbfgs'] #taking different hyperparameters to regularize the logistic regresson model
    multi_class=['auto']
    a=[]
    for i in solver:
        lr=LogisticRegression(solver=i,max_iter=100000)   #tuning the model each time with a new hyperparameter
        lr.fit(x_train,y_train)
        y_val_pred=lr.predict(x_val)
        acc=round(accuracy_score(y_val_pred,y_val),4)*100
        a.append(acc)
    m=max(a)       #getting the maximum accuracy from validation set
    p=a.index(m)   #getting the index of the max_accuracy
    lr=LogisticRegression(solver=solver[p])  #again training the model with best hyperparameter
    x_train=np.concatenate((x_train,x_val))  #Now combining both training and validation data
    y_train=np.concatenate((y_train,y_val))  #Now combing the target values of training and validation data
    lr.fit(x_train,y_train)
    y_test_pred=lr.predict(x_test)   #fitting the training data into model
    print("Model-2 : Logistic Regression")  
    acc_t=round(accuracy_score(y_test_pred,y_test),4)*100 #accuracy of the model
    print("Accuracy of Model 2 on test set : ",acc_t)
    pre=round(precision_score(y_test_pred,y_test,average='macro'),4)*100   #precision score
    print("Precision of Model 2 on test set : ",pre)
    rec=round(recall_score(y_test_pred,y_test,average='macro'),4)*100
    print("Recall of Model 2 on test set : ",rec)      #recall_score
    f_score=round(f1_score(y_test_pred,y_test,average='macro'),4)*100
    print("F1-score of Model-2 on test set : ",f_score)    #f1_Score
    con_mat=confusion_matrix(y_test,y_test_pred,labels=[1,2,3,4,5,6,7,8]) #confusion matrix
    print("Confusion Matrix of Model-2 on test set : ")
    print(con_mat)
    print(classification_report(y_test,y_test_pred,digits=8))
    


The below model implements the DecisionTree Classification.Here we tune its different parameter and try to get the best parameter by performing holdout validation.Then we used the best parameters of the model on test-set and obtain an accuracy in between 92 and 93 percent 

In [4]:
def model3(x_train,y_train,x_val,y_val,x_test,y_test):
    criterion=['gini','entropy']          #first hyperparamter list
    max_depth=[1,10,20,50,100]            #second hyperparameter list
    feature=[]                            #list that will contain different combination of hyperparameter
    a=[]                                  #list will contain different accuracy by combining different parameters
    for i in criterion:
        for j in max_depth:
            dt=DecisionTreeClassifier(criterion=i,max_depth=j)  
            dt.fit(x_train,y_train)
            y_val_pred=dt.predict(x_val)
            acc=round(accuracy_score(y_val_pred,y_val),4)*100
            feature.append((i,j))
            a.append(acc)
    m=max(a) #getting the maximum accuracy
    p=a.index(m) #getting the index of max accuracy to obtain the best hyperparameters
    dt=DecisionTreeClassifier(criterion=feature[p][0],max_depth=feature[p][1])
    x_train=np.concatenate((x_train,x_val))  #Now combining both training and validation data
    y_train=np.concatenate((y_train,y_val))  #Now combing the target values of training and validation data
    dt.fit(x_train,y_train)  #fitting the training data into the model
    y_test_pred=dt.predict(x_test)   #predicting the test data
    print("Model-3: Decision Tree ")
    acc_t=round(accuracy_score(y_test_pred,y_test),4)*100    #accuracy of the predicting model
    print("Accuracy of Model 3 on test set : ",acc_t)
    pre=round(precision_score(y_test_pred,y_test,average='macro'),4)*100     #precision of the predicting model
    print("Precision of Model 3 on test set : ",pre)
    rec=round(recall_score(y_test_pred,y_test,average='macro'),4)*100        #recall_Score of the model
    print("Recall of Model 3 on test set : ",rec)
    f_score=round(f1_score(y_test_pred,y_test,average='macro'),4)*100           #f1_score of the model
    print("F1-score of Model-3 on test set : ",f_score)
    con_mat=confusion_matrix(y_test,y_test_pred,labels=[1,2,3,4,5,6,7,8])      #confusion matrix of the model
    print("Confusion Matrix of Model-3 on test set : ")
    print(con_mat)
    print(classification_report(y_test,y_test_pred,digits=8))
    

    
            

The given below code performs Naive Bayes analysis on the given datasets .As NaiveBayes much do not have any parameters to tune .So I directly trained the model and got an accuracy of around 86 percent.

In [5]:
def model4(x_train,y_train,x_val,y_val,x_test,y_test):
    gnb=GaussianNB()
    x_train=np.concatenate((x_train,x_val))  #Now combining both training and validation data
    y_train=np.concatenate((y_train,y_val))  #Now combing the target values of training and validation data
    gnb.fit(x_train,y_train)
    y_test_pred=gnb.predict(x_test)
    print("Model-4: Naive Bayes ")
    acc_t=round(accuracy_score(y_test_pred,y_test),4)*100
    print("Accuracy of Model 4 on test set : ",acc_t)
    pre=round(precision_score(y_test_pred,y_test,average='macro'),4)*100
    print("Precision of Model 4 on test set : ",pre)
    rec=round(recall_score(y_test_pred,y_test,average='macro'),4)*100
    print("Recall of Model 4 on test set : ",rec)
    f_score=round(f1_score(y_test_pred,y_test,average='macro'),4)*100
    print("F1-score of Model-4 on test set : ",f_score)
    con_mat=confusion_matrix(y_test,y_test_pred,labels=[1,2,3,4,5,6,7,8])
    print("Confusion Matrix of Model-4 on test set : ")
    print(con_mat)
    print(classification_report(y_test,y_test_pred,digits=8))


Given below function perform the Random Forest Classification on the given data.Hypereparameters are tuned according to the validation set and we test the best parameter on test data so that we can get an accuracy of nearly 98 percent

In [6]:
def model5(x_train,y_train,x_val,y_val,x_test,y_test):
    n_estimators=[1,10,20,100,200]    #first hyperparamter list
    criterion=['gini','entropy']      #second hyperparameter list
    feature=[]                        #list that will contain different combination of hyperparameter
    a=[]                              #list will contain different accuracy by combining different parameters
    for i in n_estimators:
        for j in criterion:
            rf=RandomForestClassifier(criterion=j,n_estimators=i)
            rf.fit(x_train,y_train)
            y_val_pred=rf.predict(x_val)
            acc=round(accuracy_score(y_val_pred,y_val),4)*100
            feature.append((i,j))
            a.append(acc)
    m=max(a)       #getting the maximum accuracy
    p=a.index(m)   #getting the index of max accuracy to obtain the best hyperparameters
    rf=RandomForestClassifier(criterion=feature[p][1],n_estimators=feature[p][0])
    x_train=np.concatenate((x_train,x_val))  #Now combining both training and validation data
    y_train=np.concatenate((y_train,y_val))  #Now combing the target values of training and validation data
    rf.fit(x_train,y_train)  #fitting the training data into the model
    y_test_pred=rf.predict(x_test)  #predicting the test data
    print("Model-5: Random-Forest ")
    acc_t=round(accuracy_score(y_test_pred,y_test),4)*100    #accuracy of the predicting model
    print("Accuracy of Model 5 on test set : ",acc_t)
    pre=round(precision_score(y_test_pred,y_test,average='macro'),4)*100   #precision of the predicting model
    print("Precision of Model 5 on test set : ",pre)
    rec=round(recall_score(y_test_pred,y_test,average='macro'),4)*100      #recall_Score of the model
    print("Recall of Model 5 on test set : ",rec)
    f_score=round(f1_score(y_test_pred,y_test,average='macro'),4)*100      #f1_score of the model
    print("F1-score of Model-5 on test set : ",f_score)
    con_mat=confusion_matrix(y_test,y_test_pred,labels=[1,2,3,4,5,6,7,8])   #confusion matrix of the model
    print("Confusion Matrix of Model-5 on test set : ")
    print(con_mat)
    print(classification_report(y_test,y_test_pred,digits=8))
    

Support Vector Machine Algorithm is performed onn the given model and accuracy obtained was 97 percent

In [7]:
def model6(x_train,y_train,x_val,y_val,x_test,y_test):
    C=[1,10,100,1000]             #first hyper-parameter list
    gamma=[0.0001,0.001,0.01,0.1,1,10]              #second hyper-parameter list
    kernel=['rbf','poly','linear']    #third hyper-parameter list
    feature=[]                        #list that will contain different combination of hyperparameter
    a=[]                              #list will contain different accuracy by combining different parameters
    for i in C:
        for j in gamma:
            for k in kernel:
                svc=SVC(C=i,gamma=j,kernel=k)
                svc.fit(x_train,y_train)
                y_val_pred=svc.predict(x_val)
                acc=round(accuracy_score(y_val_pred,y_val),4)*100
                feature.append((i,j,k))
                a.append(acc)
    m=max(a)                        #getting the maximum accuracy
    p=a.index(m)                    #getting the index of max accuracy to obtain the best hyperparameters
    print(a)
    print(feature[p])
    svc=SVC(C=feature[p][0],gamma=feature[p][1],kernel=feature[p][2])
    x_train=np.concatenate((x_train,x_val))  #Now combining both training and validation data
    y_train=np.concatenate((y_train,y_val))  #Now combing the target values of training and validation data
    svc.fit(x_train,y_train)        #fitting the training data into the model
    y_test_pred=svc.predict(x_test) #predicting the test data
    print("Model-6: Support Vector Machine ")
    acc_t=round(accuracy_score(y_test_pred,y_test),4)*100                    #accuracy of the predicting model
    print("Accuracy of Model 6 on test set : ",acc_t)
    pre=round(precision_score(y_test_pred,y_test,average='macro'),4)*100     #precision of the predicting model
    print("Precision of Model 6 on test set : ",pre)
    rec=round(recall_score(y_test_pred,y_test,average='macro'),4)*100        #recall_Score of the model
    print("Recall of Model 6 on test set : ",rec)
    f_score=round(f1_score(y_test_pred,y_test,average='macro'),4)*100        #f1_score of the model
    print("F1-score of Model-6 on test set : ",f_score)
    con_mat=confusion_matrix(y_test,y_test_pred,labels=[1,2,3,4,5,6,7,8])    #confusion matrix of the model
    print("Confusion Matrix of Model-6 on test set : ")
    print(con_mat)
    print(classification_report(y_test,y_test_pred,digits=8))
    

SGD Classification Algorithm is performed onn the given model and accuracy obtained was 93 percent

In [8]:
def model7(x_train,y_train,x_val,y_val,x_test,y_test):
    loss=['squared_hinge','modified_huber','perceptron','log','hinge']  #first hyper-parameter list
    alpha=[0.00001,0.001,0.1,0.01]                                      #second hyper-parameter list
    learning_rate=['adaptive','optimal','invscaling']                   #third hyper-parameter list
    feature=[]                                                          #list that will contain different combination of hyperparameter
    a=[]                                                                #list will contain different accuracy by combining different parameters
    for i in loss:
        for j in alpha:
            for k in learning_rate:
                    sgd=SGDClassifier(loss=i,alpha=j,learning_rate=k,eta0=1,max_iter=1000000)
                    sgd.fit(x_train,y_train)
                    y_val_pred=sgd.predict(x_val)
                    acc=round(accuracy_score(y_val_pred,y_val),4)*100
                    feature.append((i,j,k))
                    a.append(acc)
    m=max(a)                        #getting the maximum accuracy
    p=a.index(m)                    #getting the index of max accuracy to obtain the best hyperparameters
    print(feature[p])
    sgd=SGDClassifier(loss=feature[p][0],alpha=feature[p][1],learning_rate=feature[p][2],max_iter=100000,eta0=1)
    x_train=np.concatenate((x_train,x_val))  #Now combining both training and validation data
    y_train=np.concatenate((y_train,y_val))  #Now combing the target values of training and validation data
    sgd.fit(x_train,y_train)        #fitting the training data into the model
    y_test_pred=sgd.predict(x_test) #predicting the test data
    print("Model-7: SGD Method ")
    acc_t=round(accuracy_score(y_test_pred,y_test),4)*100         #accuracy of the predicting model
    print("Accuracy of Model 7 on test set : ",acc_t)
    pre=round(precision_score(y_test_pred,y_test,average='macro'),4)*100    #precision of the predicting model
    print("Precision of Model 7 on test set : ",pre)
    rec=round(recall_score(y_test_pred,y_test,average='macro'),4)*100        #recall_Score of the model
    print("Recall of Model 7 on test set : ",rec)
    f_score=round(f1_score(y_test_pred,y_test,average='macro'),4)*100        #f1_score of the model
    print("F1-score of Model-7 on test set : ",f_score)
    con_mat=confusion_matrix(y_test,y_test_pred,labels=[1,2,3,4,5,6,7,8])    #confusion matrix of the model
    print("Confusion Matrix of Model-7 on test set : ")
    print(con_mat)
    
    

It's the main fuction where dataset which was in xls format is converted into Dataframe using pandas then this data is explored and cleaned for further operation to be performed and then stored in a numpy array so that we can easily perform our task.Here different models are called in which data in the form of array is passed as arguments and obtain the metric parameters such as accuracy score,precision,recall,F1-score and confusion-matrix.From this metrics we evaluated how different models performed on the given dataset.Here every model's hyperparameters are tuned with the help of loops.The best accuracy was ovtained for Random Forest follwed by Support Vector Machine Classifier

In [ ]:
if __name__ == '__main__':
    train=pd.read_excel('cTTD_features_with_Labels/S2/trainset_60.xls')  #reading the xls file into dataframe
    validate=pd.read_excel('cTTD_features_with_Labels/S2/validate_20.xls')
    test=pd.read_excel('cTTD_features_with_Labels/S2/testset_20.xls')
    
    x_tr=train.drop(43,axis=1)    #separating the target values
    y_tr=train[43]
    x_v=validate.drop(43,axis=1)
    y_v=validate[43]
    x_te=test.drop(43,axis=1)
    y_te=test[43]
    
    x_train=x_tr.to_numpy()        # converting dataframe to numpy array
    y_train=y_tr.to_numpy()
    x_val=x_v.to_numpy()
    y_val=y_v.to_numpy()
    x_test=x_te.to_numpy()
    y_test=y_te.to_numpy()
    
    sc=StandardScaler()
    x_train=sc.fit_transform(x_train)
    x_val=sc.fit_transform(x_val)
    x_test=sc.fit_transform(x_test)
    
    model1(x_train,y_train,x_val,y_val,x_test,y_test)
    print("==========================================================================================================")
    
    model2(x_train,y_train,x_val,y_val,x_test,y_test)
    print("==========================================================================================================")
    
    model3(x_train,y_train,x_val,y_val,x_test,y_test)
    print("==========================================================================================================")
    
    model4(x_train,y_train,x_val,y_val,x_test,y_test)
    print("==========================================================================================================")
    
    model5(x_train,y_train,x_val,y_val,x_test,y_test)
    print("==========================================================================================================")
    
    model6(x_train,y_train,x_val,y_val,x_test,y_test)
    print("==========================================================================================================")
    
    s
    
    
    
    
    

Model-1 : K-Nearest Neighbors
Accuracy of Model 1 on test set :  96.39
Precision of Model 1 on test set :  96.44
Recall of Model 1 on test set :  96.46000000000001
F1-score of Model-1 on test set :  96.43
Confusion Matrix of Model-1 on test set : 
[[877   0   1   0   0   1   0   0]
 [  0 884   0   3   0   1   0   0]
 [  0   0 871   5   2   0   0   0]
 [  0   0   7 839   3  13  35   0]
 [  0   0   2   0 848  23   1   0]
 [  0   5   3  11  12 836  16   0]
 [  0   1   0  51   3  53 790   0]
 [  0   0   1   1   0   0   0 841]]
              precision    recall  f1-score   support

           1  1.00000000 0.99772469 0.99886105       879
           2  0.99325843 0.99549550 0.99437570       888
           3  0.98418079 0.99202733 0.98808849       878
           4  0.92197802 0.93534002 0.92861096       897
           5  0.97695853 0.97025172 0.97359357       874
           6  0.90183387 0.94677237 0.92375691       883
           7  0.93824228 0.87973274 0.90804598       898
           8  1.0

c:\users\dell\appdata\local\programs\python\python37\lib\site-packages\sklearn\linear_model\logistic.py:469: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)
c:\users\dell\appdata\local\programs\python\python37\lib\site-packages\sklearn\linear_model\logistic.py:469: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)
c:\users\dell\appdata\local\programs\python\python37\lib\site-packages\sklearn\linear_model\logistic.py:469: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)
c:\users\dell\appdata\local\programs\python\python37\lib\site-packages\sklearn\linear_model\logistic.py:469: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the mu

Model-2 : Logistic Regression
Accuracy of Model 2 on test set :  97.72999999999999
Precision of Model 2 on test set :  97.76
Recall of Model 2 on test set :  97.74000000000001
F1-score of Model-2 on test set :  97.75
Confusion Matrix of Model-2 on test set : 
[[879   0   0   0   0   0   0   0]
 [  0 888   0   0   0   0   0   0]
 [  0   0 869   6   1   2   0   0]
 [  0   0   6 837   1   3  42   8]
 [  0   0   0   0 873   1   0   0]
 [  0   5   6   4   2 856  10   0]
 [  0   0   0  39   2  21 836   0]
 [  0   0   0   1   0   0   0 842]]
              precision    recall  f1-score   support

           1  1.00000000 1.00000000 1.00000000       879
           2  0.99440090 1.00000000 0.99719259       888
           3  0.98637911 0.98974943 0.98806140       878
           4  0.94363021 0.93311037 0.93834081       897
           5  0.99317406 0.99885584 0.99600685       874
           6  0.96942242 0.96942242 0.96942242       883
           7  0.94144144 0.93095768 0.93617021       898
     

The main-objective was to give the results obtained from SVM and SGD Classifier:

1. Accuracy from Support Vector Machine = 97
2. Accuracy from SGD Method = 94