Basically, the aim of the task is to share the results (accuracy score/performance) of two machine learning model i.e Support Vector Machine and Stochastic Gradient Descent Method.But,I have used many other classification algorithms to see which performs the best among all the algorithms.
The datasets was provided to perform the task.It was boardly divided such that 60% of data was for training the model,20% of data was to validate the model such that we can tune its hyperparameters and its performance is improved and the rest 20% was for testing purpose.


In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier,ExtraTreesClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.gaussian_process import  GaussianProcessClassifier
from sklearn.metrics import accuracy_score,precision_score,recall_score,confusion_matrix,f1_score,classification_report
from sklearn.model_selection import GridSearchCV
from sklearn.preprocessing import StandardScaler



In [2]:
def model1(x_train,y_train,x_test,y_test):
    k_range=[3,7,9,13,15,19,23,25]
    param_grid=dict(n_neighbors=k_range)
    grid = GridSearchCV(KNeighborsClassifier(), param_grid, cv=5, scoring='accuracy')
    grid.fit(x_train,y_train)
    print("Model-1 : K-Nearest Neighbors ")
    y_test_pred=grid.predict(x_test)
    acc_t=round(accuracy_score(y_test_pred,y_test),4)*100
    print("Accuracy of Model 1 on test set : ",acc_t)
    pre=round(precision_score(y_test_pred,y_test,average='macro'),4)*100
    print("Precision of Model 1 on test set : ",pre)
    rec=round(recall_score(y_test_pred,y_test,average='macro'),4)*100
    print("Recall of Model 1 on test set : ",rec)
    f_score=round(f1_score(y_test_pred,y_test,average='macro'),4)*100
    print("F1-score of Model-1 on test set : ",f_score)
    con_mat=confusion_matrix(y_test,y_test_pred,labels=[1,2,3,4,5,6,7,8])
    print("Confusion Matrix of Model-1 on test set : ")
    print(con_mat)
    print(classification_report(y_test,y_test_pred,digits=8))
    return grid.best_params_

    
    
    

In [3]:
def model2(x_train,y_train,x_test,y_test):
    param_grid={'solver':['liblinear','newton-cg','sag'],'max_iter':[10000]}
    grid = GridSearchCV(LogisticRegression(), param_grid, cv=5, scoring='accuracy')
    grid.fit(x_train,y_train)
    print("Model-2 : Logistic Regression ")
    y_test_pred=grid.predict(x_test)
    acc_test=round(accuracy_score(y_test_pred,y_test),4)*100
    print("Accuracy of Model 2 on test set : ",acc_test)
    pre=round(precision_score(y_test_pred,y_test,average='macro'),4)*100
    print("Precision of Model 2 on test set : ",pre)
    rec=round(recall_score(y_test_pred,y_test,average='macro'),4)*100
    print("Recall of Model 2 on test set : ",rec)
    f_score=round(f1_score(y_test_pred,y_test,average='macro'),4)*100
    print("F1-score of Model-2 on test set : ",f_score)
    con_mat=confusion_matrix(y_test,y_test_pred,labels=[1,2,3,4,5,6,7,8])
    print("Confusion Matrix of Model-2 on test set : ")
    print(con_mat)
    print(classification_report(y_test,y_test_pred,digits=8))
    return grid.best_params_

    
    

In [4]:
def model3(x_train,y_train,x_test,y_test):
    param_grid={'criterion':['gini','entropy'],'max_depth':[5,7,9,13,15,23],'min_samples_leaf':[1,2,5]}
    grid = GridSearchCV(DecisionTreeClassifier(), param_grid, cv=5, scoring='accuracy')
    grid.fit(x_train,y_train)
    print("Model-3 : Decision Tree ")
    y_test_pred=grid.predict(x_test)
    acc_test=round(accuracy_score(y_test_pred,y_test),4)*100
    print("Accuracy of Model 3 on test set : ",acc_test)
    pre=round(precision_score(y_test_pred,y_test,average='macro'),4)*100
    print("Precision of Model 3 on test set : ",pre)
    rec=round(recall_score(y_test_pred,y_test,average='macro'),4)*100
    print("Recall of Model 3 on test set : ",rec)
    f_score=round(f1_score(y_test_pred,y_test,average='macro'),4)*100
    print("F1-score of Model-3 on test set : ",f_score)
    con_mat=confusion_matrix(y_test,y_test_pred,labels=[1,2,3,4,5,6,7,8])
    print("Confusion Matrix of Model-3 on test set : ")
    print(con_mat)
    print(classification_report(y_test,y_test_pred,digits=8))
    return grid.best_params_

    


In [5]:
def model5(x_train,y_train,x_test,y_test):
    param_grid={'n_estimators':[1,10,20,50,100],'criterion':['gini','entropy'],'max_depth':[5,6,8,13,15,23,25]}
    grid = GridSearchCV(RandomForestClassifier(), param_grid, cv=5, scoring='accuracy')
    grid.fit(x_train,y_train)
    print("Model-5 : Random Forest Classification  ")
    y_test_pred=grid.predict(x_test)
    acc_test=round(accuracy_score(y_test_pred,y_test),4)*100
    print("Accuracy of Model 5 on test set : ",acc_test)
    pre=round(precision_score(y_test_pred,y_test,average='macro'),4)*100
    print("Precision of Model 5 on test set : ",pre)
    rec=round(recall_score(y_test_pred,y_test,average='macro'),4)*100
    print("Recall of Model 5 on test set : ",rec)
    f_score=round(f1_score(y_test_pred,y_test,average='macro'),4)*100
    print("F1-score of Model-5 on test set : ",f_score)
    con_mat=confusion_matrix(y_test,y_test_pred,labels=[1,2,3,4,5,6,7,8])
    print("Confusion Matrix of Model-5 on test set : ")
    print(con_mat)
    print(classification_report(y_test,y_test_pred,digits=8))
    return grid.best_params_

    

In [6]:
def model6(x_train,y_train,x_test,y_test):
    param_grid={'C':[1,10,100,100],'gamma':['auto',0.1,0.01,0.001],'kernel':['rbf','poly']}
    grid = GridSearchCV(SVC(), param_grid, cv=5, scoring='accuracy')
    grid.fit(x_train,y_train)
    print("Model-6 : Support Vector Machine  ")
    y_test_pred=grid.predict(x_test)
    acc_test=round(accuracy_score(y_test_pred,y_test),4)*100
    print("Accuracy of Model 6 on test set : ",acc_test)
    pre=round(precision_score(y_test_pred,y_test,average='macro'),4)*100
    print("Precision of Model 6 on test set : ",pre)
    rec=round(recall_score(y_test_pred,y_test,average='macro'),4)*100
    print("Recall of Model 6 on test set : ",rec)
    f_score=round(f1_score(y_test_pred,y_test,average='macro'),4)*100
    print("F1-score of Model-6 on test set : ",f_score)
    con_mat=confusion_matrix(y_test,y_test_pred,labels=[1,2,3,4,5,6,7,8])
    print("Confusion Matrix of Model-6 on test set : ")
    print(con_mat)
    print(classification_report(y_test,y_test_pred,digits=8))
    return grid.best_params_

    

In [7]:
if __name__ == '__main__':
    train=pd.read_excel('cTTD_features_with_Labels/S2/trainset_60.xls')  #reading the xls file into dataframe
    validate=pd.read_excel('cTTD_features_with_Labels/S2/validate_20.xls')
    test=pd.read_excel('cTTD_features_with_Labels/S2/testset_20.xls')
    
    x_tr=train.drop(43,axis=1)    #separating the target values
    y_tr=train[43]
    x_v=validate.drop(43,axis=1)
    y_v=validate[43]
    x_te=test.drop(43,axis=1)
    y_te=test[43]
    
    x_train=x_tr.to_numpy()        # converting dataframe to numpy array
    y_train=y_tr.to_numpy()
    x_val=x_v.to_numpy()
    y_val=y_v.to_numpy()
    x_test=x_te.to_numpy()
    y_test=y_te.to_numpy()
    
    sc=StandardScaler()
    x_train=sc.fit_transform(x_train)       #standardizing the features for better traing process
    x_val=sc.fit_transform(x_val)
    x_test=sc.fit_transform(x_test)
    estimator=[]
    
    x_train=np.concatenate((x_train,x_val))  #Now combining both training and validation data
    y_train=np.concatenate((y_train,y_val))  #Now combing the target values of training and validation data
    
    
    estimator.append(model1(x_train,y_train,x_test,y_test))
    print("==========================================================================================================")
    
    estimator.append(model2(x_train,y_train,x_test,y_test))
    print("==========================================================================================================")
    
    
    estimator.append(model3(x_train,y_train,x_test,y_test))
    print("==========================================================================================================")
    
    estimator.append(model5(x_train,y_train,x_test,y_test))
    print("==========================================================================================================")
    
    estimator.append(model6(x_train,y_train,x_test,y_test))
    print("==========================================================================================================")
    
    print(estimator)
    
   
    ''' model7(x_train,x_test,Y_train,y_test,estimator)
    print("===========================================================================================================")
    
    model8(x_train,x_test,Y_train,y_test,estimator)
    print("===========================================================================================================")
    
    model9(x_train,x_test,Y_train,y_test,estimator)
    print("===========================================================================================================")
    
    model10(x_train,x_test,Y_train,y_test,estimator)
    print("===========================================================================================================")'''

Model-1 : K-Nearest Neighbors 
Accuracy of Model 1 on test set :  96.96000000000001
Precision of Model 1 on test set :  97.0
Recall of Model 1 on test set :  97.00999999999999
F1-score of Model-1 on test set :  96.99
Confusion Matrix of Model-1 on test set : 
[[876   0   1   0   2   0   0   0]
 [  0 888   0   0   0   0   0   0]
 [  0   0 873   5   0   0   0   0]
 [  0   0  10 849   1   4  33   0]
 [  0   1   1   2 857  13   0   0]
 [  0   9   2  16   7 840   9   0]
 [  0   0   0  51   2  44 801   0]
 [  0   0   0   1   0   0   0 842]]
              precision    recall  f1-score   support

           1  1.00000000 0.99658703 0.99829060       879
           2  0.98886414 1.00000000 0.99440090       888
           3  0.98421646 0.99430524 0.98923513       878
           4  0.91883117 0.94648829 0.93245470       897
           5  0.98619102 0.98054920 0.98336202       874
           6  0.93229745 0.95130238 0.94170404       883
           7  0.95017794 0.89198218 0.92016083       898
     