In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier,ExtraTreesClassifier,VotingClassifier,AdaBoostClassifier,GradientBoostingClassifier,StackingClassifier,BaggingClassifier
from sklearn.preprocessing import StandardScaler 
from sklearn.metrics import accuracy_score,precision_score,recall_score,confusion_matrix,f1_score,classification_report
from xgboost import XGBClassifier


In [3]:
train=pd.read_excel('cTTD_features_with_Labels/S2/trainset_60.xls')  #reading the xls file into dataframe
validate=pd.read_excel('cTTD_features_with_Labels/S2/validate_20.xls')
test=pd.read_excel('cTTD_features_with_Labels/S2/testset_20.xls')
    
x_tr=train.drop(43,axis=1)    #separating the target values
y_tr=train[43]
x_v=validate.drop(43,axis=1)
y_v=validate[43]
x_te=test.drop(43,axis=1)
y_te=test[43]
    
x_train=x_tr.to_numpy()        # converting dataframe to numpy array
y_train=y_tr.to_numpy()
x_val=x_v.to_numpy()
y_val=y_v.to_numpy()
x_test=x_te.to_numpy()
y_test=y_te.to_numpy()
    
sc=StandardScaler()
x_train=sc.fit_transform(x_train)       #standardizing the features for better traing process
x_val=sc.fit_transform(x_val)
x_test=sc.fit_transform(x_test)

In [4]:
x_train=np.concatenate((x_train,x_val))  #Now combining both training and validation data
y_train=np.concatenate((y_train,y_val))  #Now combing the target values of training and validation data

In [5]:
estimator=[('svc',SVC(C=100,kernel='rbf',random_state=0,gamma='auto',class_weight='balanced')),('rf',RandomForestClassifier(n_estimators=200,criterion='entropy',max_depth=23)),
          ('lg',LogisticRegression(solver='newton-cg')),('knn',KNeighborsClassifier(n_neighbors=5)),
          ('mt',ExtraTreesClassifier(n_estimators=200,criterion='entropy',max_depth=23))]

In [ ]:
estimator

In [ ]:
vot_hard=VotingClassifier(estimators = estimator, voting ='hard') 
vot_hard.fit(x_train, y_train)
y_test_pred=vot_hard.predict(x_test)
acc_t=round(accuracy_score(y_test_pred,y_test),4)*100    #accuracy of the predicting model
print("Accuracy of Model 7 on test set : ",acc_t)
pre=round(precision_score(y_test_pred,y_test,average='macro'),4)*100   #precision of the predicting model
print("Precision of Model 7 on test set : ",pre)
rec=round(recall_score(y_test_pred,y_test,average='macro'),4)*100      #recall_Score of the model
print("Recall of Model 7 on test set : ",rec)
f_score=round(f1_score(y_test_pred,y_test,average='macro'),4)*100      #f1_score of the model
print("F1-score of Model-7 on test set : ",f_score)
con_mat=confusion_matrix(y_test,y_test_pred,labels=[1,2,3,4,5,6,7,8])   #confusion matrix of the model
print("Confusion Matrix of Model-7 on test set : ")
print(con_mat)
print(classification_report(y_test,y_test_pred,digits=8))


In [ ]:
bag=BaggingClassifier(base_estimator=SVC(C=100,gamma='auto'),n_estimators=200,random_state=5) 
bag.fit(x_train, y_train)
y_test_pred=bag.predict(x_test)
acc_t=round(accuracy_score(y_test_pred,y_test),4)*100    #accuracy of the predicting model
print("Accuracy of Model 8 on test set : ",acc_t)
pre=round(precision_score(y_test_pred,y_test,average='macro'),4)*100   #precision of the predicting model
print("Precision of Model 8 on test set : ",pre)
rec=round(recall_score(y_test_pred,y_test,average='macro'),4)*100      #recall_Score of the model
print("Recall of Model 8 on test set : ",rec)
f_score=round(f1_score(y_test_pred,y_test,average='macro'),4)*100      #f1_score of the model
print("F1-score of Model-8 on test set : ",f_score)
con_mat=confusion_matrix(y_test,y_test_pred,labels=[1,2,3,4,5,6,7,8])   #confusion matrix of the model
print("Confusion Matrix of Model-8 on test set : ")
print(con_mat)
print(classification_report(y_test,y_test_pred,digits=8))


In [ ]:
ada=AdaBoostClassifier(base_estimator=SVC(C=100,gamma='auto',kernel='rbf',random_state=0,class_weight='balanced'),n_estimators=100,learning_rate=0.1,algorithm='SAMME',random_state=4)
ada.fit(x_train,y_train)
y_test_pred=ada.predict(x_test)
acc_t=round(accuracy_score(y_test_pred,y_test),4)*100    #accuracy of the predicting model
print("Accuracy of Model 8 on test set : ",acc_t)
pre=round(precision_score(y_test_pred,y_test,average='macro'),4)*100   #precision of the predicting model
print("Precision of Model 8 on test set : ",pre)
rec=round(recall_score(y_test_pred,y_test,average='macro'),4)*100      #recall_Score of the model
print("Recall of Model 8 on test set : ",rec)
f_score=round(f1_score(y_test_pred,y_test,average='macro'),4)*100      #f1_score of the model
print("F1-score of Model-8 on test set : ",f_score)
con_mat=confusion_matrix(y_test,y_test_pred,labels=[1,2,3,4,5,6,7,8])   #confusion matrix of the model
print("Confusion Matrix of Model-8 on test set : ")
print(con_mat)
print(classification_report(y_test,y_test_pred,digits=8))





In [1]:
gbc=GradientBoostingClassifier(n_estimators=200,learning_rate=0.1,subsample=1,random_state=0)
gbc.fit(x_train,y_train)
y_test_pred=gbc.predict(x_test)
acc_t=round(accuracy_score(y_test_pred,y_test),4)*100    #accuracy of the predicting model
print("Accuracy of Model 8 on test set : ",acc_t)
pre=round(precision_score(y_test_pred,y_test,average='macro'),4)*100   #precision of the predicting model
print("Precision of Model 8 on test set : ",pre)
rec=round(recall_score(y_test_pred,y_test,average='macro'),4)*100      #recall_Score of the model
print("Recall of Model 8 on test set : ",rec)
f_score=round(f1_score(y_test_pred,y_test,average='macro'),4)*100      #f1_score of the model
print("F1-score of Model-8 on test set : ",f_score)
con_mat=confusion_matrix(y_test,y_test_pred,labels=[1,2,3,4,5,6,7,8])   #confusion matrix of the model
print("Confusion Matrix of Model-8 on test set : ")
print(con_mat)
print(classification_report(y_test,y_test_pred,digits=8))




NameError: name 'GradientBoostingClassifier' is not defined

In [ ]:
stc=StackingClassifier(estimators=estimator,final_estimator=SVC(C=100,kernel='rbf',random_state=0,gamma='auto',class_weight='balanced'),cv=5)
stc.fit(x_train,y_train)
y_test_pred=stc.predict(x_test)
acc_t=round(accuracy_score(y_test_pred,y_test),4)*100    #accuracy of the predicting model
print("Accuracy of Model 8 on test set : ",acc_t)
pre=round(precision_score(y_test_pred,y_test,average='macro'),4)*100   #precision of the predicting model
print("Precision of Model 8 on test set : ",pre)
rec=round(recall_score(y_test_pred,y_test,average='macro'),4)*100      #recall_Score of the model
print("Recall of Model 8 on test set : ",rec)
f_score=round(f1_score(y_test_pred,y_test,average='macro'),4)*100      #f1_score of the model
print("F1-score of Model-8 on test set : ",f_score)
con_mat=confusion_matrix(y_test,y_test_pred,labels=[1,2,3,4,5,6,7,8])   #confusion matrix of the model
print("Confusion Matrix of Model-8 on test set : ")
print(con_mat)
print(classification_report(y_test,y_test_pred,digits=8))



In [9]:
svc=SVC(C=100,kernel='rbf',gamma='auto')
svc.fit(x_train,y_train)
y_test_pred=svc.predict(x_test)
acc_t=round(accuracy_score(y_test_pred,y_test),4)*100    #accuracy of the predicting model
print("Accuracy of Model 8 on test set : ",acc_t)
pre=round(precision_score(y_test_pred,y_test,average='macro'),4)*100   #precision of the predicting model
print("Precision of Model 8 on test set : ",pre)
rec=round(recall_score(y_test_pred,y_test,average='macro'),4)*100      #recall_Score of the model
print("Recall of Model 8 on test set : ",rec)
f_score=round(f1_score(y_test_pred,y_test,average='macro'),4)*100      #f1_score of the model
print("F1-score of Model-8 on test set : ",f_score)
con_mat=confusion_matrix(y_test,y_test_pred,labels=[1,2,3,4,5,6,7,8])   #confusion matrix of the model
print("Confusion Matrix of Model-8 on test set : ")
print(con_mat)
print(classification_report(y_test,y_test_pred,digits=8))




Accuracy of Model 8 on test set :  99.25
Precision of Model 8 on test set :  99.26
Recall of Model 8 on test set :  99.26
F1-score of Model-8 on test set :  99.26
Confusion Matrix of Model-8 on test set : 
[[879   0   0   0   0   0   0   0]
 [  0 888   0   0   0   0   0   0]
 [  0   0 878   0   0   0   0   0]
 [  0   0   2 885   0   0  10   0]
 [  0   0   0   0 873   1   0   0]
 [  0   0   0   0   0 881   2   0]
 [  0   0   0  30   0   7 861   0]
 [  0   0   1   0   0   0   0 842]]
              precision    recall  f1-score   support

           1  1.00000000 1.00000000 1.00000000       879
           2  1.00000000 1.00000000 1.00000000       888
           3  0.99659478 1.00000000 0.99829449       878
           4  0.96721311 0.98662207 0.97682119       897
           5  1.00000000 0.99885584 0.99942759       874
           6  0.99100112 0.99773499 0.99435666       883
           7  0.98625430 0.95879733 0.97233202       898
           8  1.00000000 0.99881376 0.99940653       843

 

In [ ]:
xgb=XGBClassifier(n_estimators=500)
xgb.fit(x_train,y_train)

In [ ]:
y_test_pred=xgb.predict(x_test)
acc_t=round(accuracy_score(y_test_pred,y_test),4)*100    #accuracy of the predicting model
print("Accuracy of Model 8 on test set : ",acc_t)
pre=round(precision_score(y_test_pred,y_test,average='macro'),4)*100   #precision of the predicting model
print("Precision of Model 8 on test set : ",pre)
rec=round(recall_score(y_test_pred,y_test,average='macro'),4)*100      #recall_Score of the model
print("Recall of Model 8 on test set : ",rec)
f_score=round(f1_score(y_test_pred,y_test,average='macro'),4)*100      #f1_score of the model
print("F1-score of Model-8 on test set : ",f_score)
con_mat=confusion_matrix(y_test,y_test_pred,labels=[1,2,3,4,5,6,7,8])   #confusion matrix of the model
print("Confusion Matrix of Model-8 on test set : ")
print(con_mat)
print(classification_report(y_test,y_test_pred,digits=8))




In [ ]:
from keras.models import Sequential
from keras.la